$rally_api_key="_abc233"
$rally_server="https://rally1.rallydev.com"
$rally_workspace="Workspace Name"
$smtp_host="hostname or ip"
$smtp_port="port"
$from_address="from email address"
$to_address="to email address"